# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: swift

cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods -v 1.5.3 --no-rdoc --no-ri --no-document --quiet
- pod install --project-directory=Example


script:
- cd Example/
- xcodebuild test -enableCodeCoverage YES -workspace XKit.xcworkspace -scheme XKit_Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.1,name=iPhone XS' ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'XKit'