name: XKit Unit Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  UnitTest:
    name: UnitTest
    runs-on: macos-latest
    strategy:
        fail-fast: false
        matrix:
          destination: [iOS]
    steps:
      - uses: actions/checkout@v2
      - name: Test via xcodebuild
        run: |
          DESTINATION="platform=iOS Simulator,name=iPhone 12 Pro"
          SCHEME="XKit"
          xcodebuild -showdestinations \
            -scheme ${SCHEME}
          xcodebuild clean test \
            -destination "${DESTINATION}" \
            -scheme ${SCHEME} \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=YES
